export const ADD_PROGRAM_REQUEST = "ADD_PROGRAM_REQUEST";
export const ADD_PROGRAM_SUCCESS = "ADD_PROGRAM_SUCCESS";
export const ADD_PROGRAM_FAIL = "ADD_PROGRAM_FAIL";
export const ADD_PROGRAM_RESET = "ADD_PROGRAM_RESET";

export const ADD_CLASS_REQUEST = "ADD_CLASS_REQUEST";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAIL = "ADD_CLASS_FAIL";
export const ADD_CLASS_RESET = "ADD_CLASS_RESET";

export const FIND_CLASS_REQUEST = "FIND_CLASS_REQUEST";
export const FIND_CLASS_SUCCESS = "FIND_CLASS_SUCCESS";
export const FIND_CLASS_FAIL = "FIND_CLASS_FAIL";
export const FIND_CLASS_RESET = "FIND_CLASS_RESET";
