export const ENROLL_STUDENT_REQUEST = "ENROLL_STUDENT_REQUEST";
export const ENROLL_STUDENT_SUCCESS = "ENROLL_STUDENT_SUCCESS";
export const ENROLL_STUDENT_FAIL = "ENROLL_STUDENT_FAIL";
export const ENROLL_STUDENT_RESET = "ENROLL_STUDENT_RESET";

export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAIL = "CONTACT_US_FAIL";
export const CONTACT_US_RESET = "CONTACT_US_RESET";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_RESET = "LOGIN_RESET";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_RESET = "LOGOUT_RESET";
